### ISSUE TITLE
setting currentWorkingDirectory

### ISSUE THREAD

**Issue by agreif** [greydot/hdaemonize#4]
Hi,

I am trying to daemonize a yesod app with the following code:

import System.Posix.Daemonize

```
main :: IO ()
main = serviced stillAlive

stillAlive :: CreateDaemon ()
stillAlive = simpleDaemon { program = stillAliveMain
                          , user = Just "myuser"
                          , group = Just "mygroup" }

stillAliveMain :: () -> IO ()
stillAliveMain _ = appMain
```

it seems that in `stillAliveMain`  the currentWorkingDirectory is '/'.
Question how can I change it, so that yesod can determine relative paths (eg. for the config dir)?

thanks,
Alex.

**Comment by greydot** [comment]
You could use changeWorkingDirectory from System.Posix.Directory (unix).

**Comment by agreif** [comment]
thanks.
I also could set it with 'System.Directory.setCurrentDirectory'.

thanks,
ALex.

**Comment by greydot** [comment]
You're welcome.
